# processor-sink-deployment.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: processor-sink-config
data:
  DATABASE_URL: "Placeholder"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor-sink
  labels:
    app: processor-sink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor-sink
  template:
    metadata:
      labels:
        app: processor-sink
    spec:
      containers:
      - name: processor-sink
        # IMPORTANT: Replace with your ECR image URI
        image: 677276120570.dkr.ecr.us-east-1.amazonaws.com/alert:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: processor-sink-config