/**
 * @fileoverview gRPC-Web generated client stub for health
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: health.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as health_pb from './health_pb'; // proto import: "health.proto"


export class HealthServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetAlerts = new grpcWeb.MethodDescriptor(
    '/health.HealthService/GetAlerts',
    grpcWeb.MethodType.UNARY,
    health_pb.GetAlertsRequest,
    health_pb.GetAlertsResponse,
    (request: health_pb.GetAlertsRequest) => {
      return request.serializeBinary();
    },
    health_pb.GetAlertsResponse.deserializeBinary
  );

  getAlerts(
    request: health_pb.GetAlertsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<health_pb.GetAlertsResponse>;

  getAlerts(
    request: health_pb.GetAlertsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: health_pb.GetAlertsResponse) => void): grpcWeb.ClientReadableStream<health_pb.GetAlertsResponse>;

  getAlerts(
    request: health_pb.GetAlertsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: health_pb.GetAlertsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/health.HealthService/GetAlerts',
        request,
        metadata || {},
        this.methodDescriptorGetAlerts,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/health.HealthService/GetAlerts',
    request,
    metadata || {},
    this.methodDescriptorGetAlerts);
  }

  methodDescriptorGetDeviceHistory = new grpcWeb.MethodDescriptor(
    '/health.HealthService/GetDeviceHistory',
    grpcWeb.MethodType.UNARY,
    health_pb.GetDeviceHistoryRequest,
    health_pb.GetDeviceHistoryResponse,
    (request: health_pb.GetDeviceHistoryRequest) => {
      return request.serializeBinary();
    },
    health_pb.GetDeviceHistoryResponse.deserializeBinary
  );

  getDeviceHistory(
    request: health_pb.GetDeviceHistoryRequest,
    metadata?: grpcWeb.Metadata | null): Promise<health_pb.GetDeviceHistoryResponse>;

  getDeviceHistory(
    request: health_pb.GetDeviceHistoryRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: health_pb.GetDeviceHistoryResponse) => void): grpcWeb.ClientReadableStream<health_pb.GetDeviceHistoryResponse>;

  getDeviceHistory(
    request: health_pb.GetDeviceHistoryRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: health_pb.GetDeviceHistoryResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/health.HealthService/GetDeviceHistory',
        request,
        metadata || {},
        this.methodDescriptorGetDeviceHistory,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/health.HealthService/GetDeviceHistory',
    request,
    metadata || {},
    this.methodDescriptorGetDeviceHistory);
  }

}

